### ISSUE TITLE
01_schema.sql

### ISSUE THREAD

**Issue by jacquestremblay** [guyfrancoeur/INF3080_A2019_TP#10]
Bonjour,
Il est mentionné dans l'énoncé que le fichier 01_schema.sql sera exécuté 2 fois. 
Doit-on ajouter dans notre fichier un mécanisme qui vérifie si la table existe déjà et donc dans ce cas effacer celle-ci avant sa création ?

Merci

**Comment by ammarhamad** [comment]
Bonjour
Oui c’est beau vous pouvez faire cela!

Ammar

Sent from my iPhone

On Oct 13, 2019, at 4:59 PM, Jacques Tremblay <notifications@github.com> wrote:

﻿

Bonjour,
Il est mentionné dans l'énoncé que le fichier 01_schema.sql sera exécuté 2 fois.
Doit-on ajouter dans notre fichier un mécanisme qui vérifie si la table existe déjà et donc dans ce cas effacer celle-ci avant sa création ?

Merci

**Comment by paulrufin** [comment]
Bonjour, et si on ne le fait pas ? Est-ce qu’on sera pénalisé ?
Que se passera-t-il au niveau de la correction ?

**Comment by guyfrancoeur** [comment]
Bonjour,

@paulrufin, Assurez-vous de ne pas laisser le `HASARD` prendre le contrôle de votre travail.

@tous, Nous voulons un comportement déterministe.

Lâche pas!

GF

**Comment by ammarhamad** [comment]
Bonjour
Avant, d’exécuter votre script vous faire un Drop table  à chaque table et la liste des Tables de votre système et cela peut être inclus au début de votre script

Ammar

Sent from my iPhone

On Oct 13, 2019, at 11:46 PM, paulrufin <notifications@github.com> wrote:

﻿

Bonjour, et si on ne le fait pas ? Est-ce qu’on sera pénalisé ?
Que se passera-t-il au niveau de la correction ?
