### ISSUE TITLE
02_charger.sql et 04a_query.sql

### ISSUE THREAD

**Issue by robidouux** [guyfrancoeur/INF3080_A2019_TP#11]
02_charger.sql

Tous les données chargés sont inventées? On choisi combien on veut en mettre?

04a_query.sql 
 
À quoi ressemble une soumission? Est-ce qu'il faut retourner chaque coût et l'estimation totale ou seulement l'estimation totale?

**Comment by guyfrancoeur** [comment]
Allo,

Oui, pour 02_charger.sql, c'est libre. 3+ lignes normalement afin de bien vérifier le comportement de votre schéma;

Voir l'image UX image 2 
Une soumission est contient l'information (lien) sur le chargement et combien coute chacun des camions disponibles pour transporter la demande.

Cordialement,

GF
