### ISSUE TITLE
le resultat de query

### ISSUE THREAD

**Issue by Xuquanzhang** [guyfrancoeur/INF3080_A2019_TP#12]
par rapport de' 04a_query.sql, 04b_query.sql' , quel type de résultat on attend? une seule colonne de pk, ou une table avec tous les attributs?
une auter question sur le format de cp.txt pour travail en équipe de 2?

**Comment by ammarhamad** [comment]
Bonjour
On attend pour la requête ' 04a_query.sql' : La liste des soumissions générées pour le 30 septembre pour le client 4. Voir graphique de soumission et afficher les données de la soumission. Vous n'avez pas besoin d'afficher un graphique.

Pour la deuxime requête, la liste des camions en voyage (avec tous les attributs pertinentes de camion)

Ammar

________________________________
De : Xuquanzhang [notifications@github.com]
Envoyé : 18 octobre 2019 16:28
À : guyfrancoeur/INF3080_A2019_TP
Cc : Subscribed
Objet : [guyfrancoeur/INF3080_A2019_TP] le resultat de query (#12)


par rapport de' 04a_query.sql, 04b_query.sql' , quel type de résultat on attend? une seule colonne de pk, ou une table avec tous les attributs?

**Comment by guyfrancoeur** [comment]
Allo,

Mettre les deux cp dans cp.txt (un par ligne)

Le proprietaire du dépôt est sur la premiere ligne.
Vous devez tous créer un dépôt.

GF
