### ISSUE TITLE
Je n’arrive pas à attribuer les droits aux collaborateurs

### ISSUE THREAD

**Issue by AdelOuldzeid** [guyfrancoeur/INF3080_A2019_TP#13]
L’option pour atteibuer les droits au collaborateurs n’apparait comment je fais?

![58C08A6D-1B9E-42CC-B360-40599C652954](https://user-images.githubusercontent.com/46725850/67137642-a85e7900-f206-11e9-8631-d726180c96d2.png)

**Comment by guyfrancoeur** [comment]
Allo,

Il n'y en a pas dans GitHub.

Vous êtes ok avec ce qui est fait.
