### ISSUE TITLE
Camion en route

### ISSUE THREAD

**Issue by carlomagnoSanchez** [guyfrancoeur/INF3080_A2019_TP#14]
Bonjour, 
j'ai quelques question:
1. Si un camion est en route, est-ce qu'on peut ajouter au soumission?
2. Est-ce qu'on ajout une route pour chaque soumission enregistre?
3. Les test 03_tester.sql à faire sont de test d'intégrité de données?

Merci

**Comment by guyfrancoeur** [comment]
Allo,

1. Théoriquement non. (il est occupé)
2. non
3. ils sont test qui ne sont pas évalué afin de vérifier tous les aspects que vous croyez important.
