### ISSUE TITLE
Liste des URL dépots du groupe 030

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3080_A2019_TP#16]
### Invalides
https://gitlab.info.uqam.ca/cj091060/inf3080_tp
https://github.com/Rehouma63/uqam/tree/master/inf3080-a2019-tp1
https://gitlab.info.uqam.ca/el_omari.imane/tp1-inf3080

**Comment by MaxNicol** [comment]
https://github.com/MaxNicol/inf3080-a2019-tp1

**Comment by jadepg** [comment]
https://github.com/jadepg/inf3080-a2019-tp1

**Comment by JCNrick** [comment]
https://github.com/JCNrick/inf3080-a2019-tp1

**Comment by amelield** [comment]
https://github.com/amelield/inf3080-a2019-tp1

**Comment by robidouux** [comment]
https://github.com/robidouux/inf3080-a2019-tp1

**Comment by SophiePl** [comment]
https://github.com/SophiePl/inf3080-a2019-tp1

**Comment by ahmedsalia** [comment]
https://github.com/ahmedsalia/inf3080-a2019-tp1.git

**Comment by mauderosie** [comment]
https://gitlab.info.uqam.ca/singcaster.maude/inf3080-a2019-tp1

**Comment by Mmasson-01** [comment]
https://gitlab.com/Armand.Briere/inf3080-a2019-tp1

**Comment by maelissteissier** [comment]
https://github.com/maelissteissier/inf3080-a2019-tp1

**Comment by Kevin-Moreau** [comment]
https://github.com/Kevin-Moreau/inf3080-a2019-tp1

**Comment by TringaAxel** [comment]
https://github.com/TringaAxel/inf3080-a2019-tp1

**Comment by Doudoumi-yuno** [comment]
https://gitlab.com/doudoumi/inf3080-a2019-tp1

**Comment by ricardoDeMedeiros** [comment]
https://github.com/ricardoDeMedeiros/inf3080-a2019-tp1

**Comment by onwilliam** [comment]
https://github.com/onwilliam/inf3080-a2019-tp1

**Comment by bmassiva** [comment]
https://github.com/bmassiva/inf3080-a2019-tp1.git

**Comment by bmassiva** [comment]
https://github.com/bmassiva/inf3080-a2019-tp1

**Comment by amarakeita** [comment]
https://github.com/amarakeita/inf3080-a2019-tp1.git

**Comment by larbi96** [comment]
https://github.com/larbi96/inf3080-a2019-tp1

**Comment by YaSeCA** [comment]
https://github.com/YaSeCA/inf3080-a2019-tp1

**Comment by amarakeita** [comment]
https://github.com/amarakeita/inf3080-a2019-tp1

**Comment by ClaudianeT** [comment]
https://github.com/ClaudianeT/inf3080-a2019-tp1.git

**Comment by lounissi1** [comment]
https://github.com/lounissi1/inf3080-a2019-tp1

**Comment by salimbsk02** [comment]
https://github.com/salimbsk02/inf3080-a2019-tp1

**Comment by stephaniefleurent** [comment]
https://gitlab.com/stephaniefleurent/inf3080-a2019-tp1

**Comment by Momo105** [comment]
https://github.com/Momo105/inf3080-a2019-tp1

**Comment by DubeJeanFrancois** [comment]
https://github.com/DubeJeanFrancois/inf3080-a2019-tp1

**Comment by jusave** [comment]
https://github.com/jusave/inf3080-a2019-tp1.git

**Comment by berserk64** [comment]
https://github.com/berserk64/inf3080-a2019-tp1

**Comment by Rehouma63** [comment]
https://github.com/Rehouma63/uqam/tree/master/inf3080-a2019-tp1

**Comment by QuentinNorbert** [comment]
https://gitlab.info.uqam.ca/cj091060/inf3080_tp

**Comment by jerome38920** [comment]
https://github.com/jusave/inf3080-a2019-tp1

**Comment by imane063** [comment]
https://gitlab.info.uqam.ca/el_omari.imane/tp1-inf3080

**Comment by OlivierLamarche** [comment]
https://gitlab.com/oli_lamarche/inf3080-a2019-tp1

**Comment by M-AF** [comment]
https://github.com/guyfrancoeur

**Comment by M-AF** [comment]
https://github.com/M-AF/inf3080-a2019-tp1/

... J'avais seulement envoyé la permission juste avant minuit

**Comment by MaximCrudu** [comment]
https://github.com/MaximCrudu/inf3080-a2019-tp1

**Comment by jeanMarieHab** [comment]
https://github.com/jeanMarieHab/inf3080-a2019-tp1

**Comment by RoiaJanM** [comment]
https://github.com/RoiaJanM/inf3080-a2019-tp1

**Comment by fabreezy** [comment]
https://github.com/RoiaJanM/inf3080-a2019-tp1

Voici notre travail, on avait pas bien compris comment tu pouvais acceder a notre repo. Si vous verifier les commits, on l'avait finit depuis hier.

**Comment by Alexisbou** [comment]
https://github.com/Alexisbou/inf3080-a2019-tp1

**Comment by Fazahrafi** [comment]
https://github.com/Fazahrafi/inf3080-a2019-tp1

**Comment by alexacl21** [comment]
https://github.com/alexacl21/inf3080-a2019-tp1

**Comment by niveenS** [comment]
https://gitlab.info.uqam.ca/shnewer.nefin/inf3080-a2019-tp1

**Comment by Rehouma63** [comment]
Bonjour, en quoi mon lien est-il invalide ?

**Comment by danielrosca977** [comment]
https://gitlab.info.uqam.ca/rosca.daniel/inf3080-a2019-tp1

**Comment by BousqueE** [comment]
https://github.com/BousqueE/inf3080-a2019-tp1

**Comment by QuentinNorbert** [comment]
https://gitlab.info.uqam.ca/cj091060/inf3080-a2019-tp1/

**Comment by imane063** [comment]
https://gitlab.info.uqam.ca/el_omari.imane/inf3080-a2019-tp1

**Comment by Rehouma63** [comment]
https://github.com/Rehouma63/inf3080-a2019-tp1

**Comment by ClickheadZ** [comment]
https://gitlab.com/Clickhead/inf3080-a2019-tp1
Alex J. Moreno

**Comment by MaxPhaneuf** [comment]
https://github.com/MaxPhaneuf/inf3080-a2019-tp1

**Comment by Imadfr** [comment]
https://github.com/Imadfr/inf3080-a2019-tp1

**Comment by MaxPhaneuf** [comment]
https://github.com/MaxPhaneuf/inf3080-a2019-tp1.git
________________________________
De : Imadfr <notifications@github.com>
Envoyé : 6 novembre 2019 15:31
À : guyfrancoeur/INF3080_A2019_TP <INF3080_A2019_TP@noreply.github.com>
Cc : Phaneuf, Maxime <phaneuf.maxime@courrier.uqam.ca>; Comment <comment@noreply.github.com>
Objet : Re: [guyfrancoeur/INF3080_A2019_TP] Liste des URL dépots du groupe 030 (#16)


https://github.com/Imadfr/inf3080-a2019-tp1

**Comment by Clampitar** [comment]
https://github.com/Clampitar/inf3080-a2019-tp1

**Comment by ClickheadZ** [comment]
https://github.com/ClickheadZ/inf3080-a2019-tp2

**Comment by imane063** [comment]
https://github.com/imane063/inf3080-a2019-tp2

**Comment by bmassiva** [comment]
git@github.com:bmassiva/inf3080-a2019-tp2.git

**Comment by bmassiva** [comment]
https://github.com/bmassiva/inf3080-a2019-tp2

**Comment by JCNrick** [comment]
https://github.com/JCNrick/inf3080-a2019-tp2

**Comment by Alexisbou** [comment]
https://github.com/Alexisbou/inf3080-a2019-tp2

**Comment by bray-vincent** [comment]
https://github.com/bray-vincent/inf3080-a2019-tp2

**Comment by MaximCrudu** [comment]
https://github.com/MaximCrudu/inf3080-a2019-tp2

**Comment by larbi96** [comment]
https://github.com/larbi96/inf3080-a2019-tp2

**Comment by MaxNicol** [comment]
https://github.com/MaxNicol/inf3080-a2019-tp2

**Comment by Momo105** [comment]
https://github.com/Momo105/inf3080-a2019-tp2

**Comment by RoiaJanM** [comment]
https://github.com/RoiaJanM/inf3080-a2019-tp2

**Comment by amarakeita** [comment]
https://github.com/amarakeita/inf3080-a2019-tp2

**Comment by fabreezy** [comment]
https://github.com/guyfrancoeur/INF3080_A2019_TP

**Comment by Rehouma63** [comment]
https://github.com/Rehouma63/inf3080-a2019-tp2

**Comment by OlivierLamarche** [comment]
https://github.com/OlivierLamarche/inf3080-a2019-tp2

**Comment by ClaudianeT** [comment]
https://github.com/ClaudianeT/inf3080-a2019-tp2
