### ISSUE TITLE
questions sur terminologie

### ISSUE THREAD

**Issue by Xuquanzhang** [guyfrancoeur/INF3080_A2019_TP#2]
Bonjour, 

J'ai misère à comprendre les terminologie de pPosition et cPosition, pRoute et cRoute, pTypeEquipment et cTypeEquipement, 'c' et 'p' siginfient quoi?  à propose du type de l'équipement, ce sont Drybox et Flatbox, quelle sont la relation entre ceux et 'c'&'p'?

j'ai une confusion sur la difinition de Grandeur, est-ce que le 30 veut dire que une chaîne de caractères de longeur de 30? mais 8,5 et 8,2 signifient quoi?

Xuquan Zhang

**Comment by ammarhamad** [comment]
Bonjour Xuquan
Pour les terminologies sont des notations hongroises. voir lien ci-dessous:
pPosition est un pointeur (float* pPosition). cPosition est de type char (char cPosition)
https://fr.wikipedia.org/wiki/Notation_hongroise
 Drybox et Flatbox, n'ont pas de relation avec ( c et p). 30 est une chaine de caractère de longueur 30. 8,5 et 8,2 sont de type short int.
cordialement
Ammar Hamad

**Comment by guyfrancoeur** [comment]
Allo,

voir #3 pour les explications.

Mais voici un scénario autre : j'ai besoin de deux tables une ville,l'autre province

Afin de ne pas perdre de temps nous allons modéliser très vite avec deux règles : 
+ ajouter un attribut avec : Nom de table avec `p` devant pour la clé;
+ ajouter un attribut : Nom de table avec `c` devant pour la description;
+ et ceci toujours

Nous pouvons donc conclure que toutes les tables auront minimum deux colonnes et que les noms de colonnes sont facilement détectable sans penser.  Le but est d'être en mesure d'écrire des requêtes SQL sans trop de difficulté et ceci très rapidement 😉 .  Car on connait deja toutes les attributs : clés et descriptions. Ce qui est un grand poucentage de toutes les requêtes à écrire.

Donc 

### Province
 + pProvince (pk)
 + cProvince (nom de la province)

### Ville
+ pVille (pk)
+ cVille (description ou le nom de la ville)
+ pProvince (fk) (dans quelle province est la ville

Continuer cet exercice en ajoutant la table pays !
