### ISSUE TITLE
questions à propos à la table de Position

### ISSUE THREAD

**Issue by Xuquanzhang** [guyfrancoeur/INF3080_A2019_TP#3]
Bonjour, 

Pourriez-vous expliquer un peu sur la table de Position? @guyfrancoeur 

la valeur de pPosition sert à quoi et à qui?
> > voir (post) suivant (gf).

Est-ce qu'il y a une relation entre pPosition et nLat&nLong?
> > voir (post) suivant (gf).

S'il y a 10 camions disponibles(ou non) pour une même position, combien de rangées seront pour la valeur de cette pPositon dans la table de Position?
> > 10 
> > il s'agit de position pour un camion.
> > tous les camions devraient avoir une position à un certain moment . N'est-ce pas ?
> > PS. dans la vie lorsque le camion bouge, le GPS met (via internet) la table à jour pour un `pCamion = x`

Merci,

X Zhang

**Comment by ammarhamad** [comment]
Bonjour
J'ai répondu à votre question.


Ce sont des notations hongroises. Dans l'énoncé de tp1, il a été mentionné.



voir ce lien: https://fr.wikipedia.org/wiki/Notation_hongroise


Cordialement


Ammar


________________________________
De : Xuquanzhang [notifications@github.com]
Envoyé : 3 octobre 2019 12:12
À : guyfrancoeur/INF3080_A2019_TP
Cc : Subscribed
Objet : [guyfrancoeur/INF3080_A2019_TP] questions à propos à la table de Position (#3)


Bonjour,

Pourriez-vous expliquer un peu sur la table de Position? @guyfrancoeur<https://github.com/guyfrancoeur>

la valeur de pPosition sert à quoi et à qui?

Est-ce qu'il y a une relation entre pPosition et nLat&nLong?

S'il y a 10 camions disponibles(ou non) pour une même position, combien de rangées seront pour la valeur de cette pPositon dans la table de Position?

Merci,

X Zhang

**Comment by Kkspike** [comment]
J'aimerais voir la réponse que vous avez donnée à cette question. La notation hongroise ne semble qu'expliquer la nomenclature des champs mais non la signification de du champ Position. Je dois dire que je me suis posé la même question: à quoi sert la donnée position si on a des champs pour la longitude et la latitude.

**Comment by ammarhamad** [comment]
Bonjour
Position est une table dont laquelle on trouve tous les positions des camions. Par contre latitude et longitude sont des attributs de la table position

Ammar


Sent from my iPhone

On Oct 3, 2019, at 2:32 PM, Kkspike <notifications@github.com<mailto:notifications@github.com>> wrote:


J'aimerais voir la réponse que vous avez donnée à cette question. La notation hongroise ne semble qu'expliquer la nomenclature des champs mais non la signification de du champ Position. Je dois dire que je me suis posé la même question: à quoi sert la donnée position si on a des champs pour la longitude et la latitude.

**Comment by guyfrancoeur** [comment]
Bonjour

La notation hongroise de sert à identifier les types des attributs seulement en regardant nom de l'attribut.

Pour nous, dans le cadre du cours INF3080 cette notation suit les directives suivantes : 
 + n numérique;
 + d date;
 + c chaine caractères;
 + b booléen (est un numeric(1) avec 0 ou 1 );
 + p primary key est toujours un nombre entier positif;

le clé étrangère ne change pas de nom donc, pCamion dans Position veux dire un clé étrangère (fk).

Nous utilisons une **notation hongroise augmenté** pour le domain des bases de données.

### Directives : 
 + la clé est toujours le nom de la table avec p devant
 + les clés ne changement jamais de nom afin de savoir si elles sont étrangères

### Position 
+ pPosition est donc la clé de la table
+ cPosition est un description de cette position
+ nLat  est la latitude
+ nLong est la longitude
+ bDisponible est un valeur entière 0 ou 1 dans un type numerique
+ pCamion est une clé étrangère

S'il manque des éléments je compléterai.

Merci pour la question.

Cordialement,
