### ISSUE TITLE
Fichier 05a_route.sh

### ISSUE THREAD

**Issue by onwilliam** [guyfrancoeur/INF3080_A2019_TP#30]
Bonjour,

À la remise faut-il lasser nos informations d'identifiant (username/password) pour sqlldr dans le fichier 05a_route.sh?

Merci

**Comment by guyfrancoeur** [comment]
Bonjour,

Non, vous pouvez à la livraison enlever le password.  Je ne vais pas l'utiliser tel quel.
Ce fichier est principalement pour vous.  Il vous permet d'acceler les tests.

PS si quelqu'un vous demande votre password, enseignant, collègue, directeur de banque ne donnez jamais votre password.  Il n'y a aucune raison logique de faire une tel chose.

On ne lâche pas.

G
