### ISSUE TITLE
on doit rajouté des entités, n'est-ce pas?

### ISSUE THREAD

**Issue by Rehouma63** [guyfrancoeur/INF3080_A2019_TP#4]
Dans l'énoncé, il y est mentionné quatres entités seulement: Position, typeDequipement, Route et Remorque. Il en manque non  ?

**Comment by ammarhamad** [comment]
Bonjour
Oui il en manque!

Ammar

Sent from my iPhone

On Oct 3, 2019, at 2:57 PM, Rehouma63 <notifications@github.com<mailto:notifications@github.com>> wrote:


Dans l'énoncé, il y est mentionné quatres entités seulement: Position, typeDequipement, Route et Remorque. Il en manque non ?
