### ISSUE TITLE
Notation hongroise

### ISSUE THREAD

**Issue by davidGht** [guyfrancoeur/INF3080_A2019_TP#5]
Bonjour

Je voulais savoir dans l'énoncé du TP1 ce que veut dire cPosition 30 dans la table Position et cRoute 30 dans la table Route ainsi que cTypeEquipement dans la table TypeEquipement.

[...]

Pour ma part je ne sais pas si le 'c' dans est indicatif du type caractère (qui ne serait pas compatible avec la valeur 30) ou s'il s'agit d'une clé étrangère faisant référence à camion (dans ce cas il faudrait que ce soit 'i' pour un type entier) ou bien s'il s'agit d'un 'c' comme pointeur vers un objet Camion.

C'est donc ma question : quel est le sens de la lettre 'c' dans ces trois attributs?

Merci

David Kavanaght

Réponse de M. Hamad

       "le cPosition veut dire que l'attribut cPosition est de type char et il est compose de 30 caractères et de même cRoute et cTypeEquipement."

**Comment by guyfrancoeur** [comment]
Allo,

Voir issues #3 

Champs (colonne) qui contiendra des caractères.
