### ISSUE TITLE
Colonnes des tables

### ISSUE THREAD

**Issue by paulrufin** [guyfrancoeur/INF3080_A2019_TP#6]
Est-ce les colonnes que vous donnez pour Route/Position/... sont les seules qui doivent se retrouver dans les table ou pouvons-nous en ajouter ?

**Comment by ammarhamad** [comment]
Vous pouvez ajouter si vous voyiez nécessaire!

Ammar

Sent from my iPhone

On Oct 6, 2019, at 5:12 PM, paulrufin <notifications@github.com<mailto:notifications@github.com>> wrote:


Est-ce les colonnes que vous donnez pour Route/Position/... sont les seules qui doivent se retrouver dans les table ou pouvons-nous en ajouter ?

**Comment by guyfrancoeur** [comment]
Bonjour,

Théoriquement, 
 + Si vous ajoutez des colonnes je ne peux pas vous y empécher !
 + Lorsque vous donnez qqc à quelqu'un il n'est pas très _gentil_ de fournir la moitié du cadeau. 😉 

Ceci dit, les 3 tables fournies sont pour une utilisation tel quelle.

La simplicité est surement votre meilleur piste pour réaliser ce travail.
