### ISSUE TITLE
Champs sur photo UI/UX

### ISSUE THREAD

**Issue by paulrufin** [guyfrancoeur/INF3080_A2019_TP#7]
La première photo montre des checkboxes comme "refrigerated", "rush", ...
Est-ce qu'on doit les prendre en compte ?

**Comment by guyfrancoeur** [comment]
Bonjour,

Non, les images sont à titre d'exemples.  Nous n'allons pas traiter tous les aspects liés au transport.

Les aspects à traiter sont ceux mentionné dans l'énoncé.
Il est possible que les images soient modifiées.

### Les items suivants **ne sont pas** nécessaire pour le tp1 : 
 + Tous les champs dans **Requirements**
 + number of skid (palettes)
+ loading time (temps de chargement)

Merci pour la question.

Cordialement,
