### ISSUE TITLE
Compagnie

### ISSUE THREAD

**Issue by paulrufin** [guyfrancoeur/INF3080_A2019_TP#8]
Est-ce qu'on parle d'une ou de plusieurs compagnies/transporteurs ? Le sujet est ambigue sur ce point.

**Comment by guyfrancoeur** [comment]
Bonjour,

Compagnie est une entité qui aura **une** ou **plusieurs** lignes de données.

Il faut voir le système comme centrale, Robert Transport, Gilbeault, Bourassa, UPS ou FedEx
 pourrait être des compagnies membre de ce système.

Cordialement,
