### ISSUE TITLE
Schéma

### ISSUE THREAD

**Issue by paulrufin** [guyfrancoeur/INF3080_A2019_TP#9]
Est-ce qu'on doit faire le schéma relationel **et** conceptuel ? 
La grille de correction mentionne l'un ou l'autre.

**Comment by guyfrancoeur** [comment]
Allo,

### modèle vs script

 +Si on parle du modèle (dessin), relationnel ou conceptuel est accepté.
 + Si on parle du script (des instructions DDL) pour la creation du schéma. Le schéma est relationnel.

Cordialement,
